### ISSUE TITLE
label.csv file

### ISSUE THREAD

**Issue by RongxiuZhong** [thuiar/MMSA#13]
hello,can you tell me how to get label.csv of MOSI?

**Comment by iyuge2** [comment]
Hi.

Label.csv can be generated with our public features in [README](https://github.com/thuiar/MMSA#datasets-and-pre-trained-berts).

For convenience, we have uploaded label.csv of SIMS / MOSI / MOSEI into Drivers in [README](https://github.com/thuiar/MMSA#datasets-and-pre-trained-berts).
