### ISSUE TITLE
想问，如果获取MOSEI关于情绪的6类标签？

### ISSUE THREAD

**Issue by pi408637535** [thuiar/MMSA#14]
你好，我从百度网盘上下载到了mosei的数据，但是csv中只有，sentiment的三类标签，想问6类情绪标签是要通过label列，按照划分区域值来获取吗

**Comment by iyuge2** [comment]
你好，我们整理的csv中是没有情绪标签的。官方开放的mosei数据集中的确包含了情绪类别，这个跟情感维度的标签值应该无法直接对应上。建议从官方数据中获取相关信息。

**Comment by pi408637535** [comment]
好的，明白了
