### ISSUE TITLE
Cannot import 'MultimodalBertForSequenceClassification' from 

### ISSUE THREAD

**Issue by NicholasGote** [thuiar/MMSA#15]
Dear author,

It showed the erro  _"found ImportError: cannot import name 'MultimodalBertForSequenceClassification' from 'pytorch_transformers.modeling_bert''_ when I enter 'run.py' command. I've installed the pytorch_transformers version 1.0.0.

Could you please help to check this problem?

**Comment by iyuge2** [comment]
@NicholasGote Hi, please see [# 9](https://github.com/thuiar/MMSA/issues/9). Thanks a lot!
