### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Company23564** [thuiar/MMSA#18]
![图片](https://user-images.githubusercontent.com/57937335/117390258-65ffa880-af20-11eb-95fb-40f21dabc038.png)

**Comment by Company23564** [comment]
Hello, I would like to ask why this is, this function exists

**Comment by iyuge2** [comment]
Hi, which feature did you use? This repo has been updated several times. I need more information to help you. Thank you~

**Comment by Company23564** [comment]
I'm running the datapre.py file to run the SIMS dataset

**Comment by FlameSky-S** [comment]
Hi, sorry for the delay. The datapre.py file is now deprecated. We've developed a new tool to extract multimodal features for MSA datasets. Please check out [this link](https://github.com/FlameSky-S/MMSA-FET) if you're still interested. Thank you.
