### ISSUE TITLE
More intuitive testing

### ISSUE THREAD

**Issue by leijue222** [thuiar/MMSA#21]
1. The `run.py` only can see the scores in the `*.log` file. Does it support tests emotion on **video which input by users**?

----

Oh, I see~. All the data had been processed to ***.pkl** file to train. So if I want test on personal input video, I should process the input video to pkl file which contain text, audio and video.

2. By the way. What is the performance of this method? Can it be **detected** emotion on video **real-time**?.

**Comment by leijue222** [comment]
By the way. What is the performance of this method? Can it be detected in real-time?

**Comment by leijue222** [comment]
What configuration needs to be modified to change the processing one by one? I modified [here](https://github.com/thuiar/MMSA/blob/b2e70bbd198ba8e8dc041f5e059c3baa2027b34a/config/config_regression.py#L740) and [here](https://github.com/thuiar/MMSA/blob/b2e70bbd198ba8e8dc041f5e059c3baa2027b34a/data/load_data.py#L141) ，Adjust the batch to 1, but still report the error dimension mismatch

**Comment by leijue222** [comment]
The problem is here:
https://github.com/thuiar/MMSA/blob/b2e70bbd198ba8e8dc041f5e059c3baa2027b34a/models/multiTask/SELF_MM.py#L138
I have to do this:
```
h = self.dropout(final_states[0].squeeze())
if len(h.shape) == 1:
    h = h.unsqueeze(0)
```
Otherwise, the batch is 1 cannot be processed.

**Comment by Columbine21** [comment]
Hi, to test the model performance of real-time video do not need to change the config file actually. You need to load the model and preprocess the video data as the same with train / test data.

**Comment by leijue222** [comment]
Thanks!
In fact, I'm trying to do it.
But I have some problems when dealing with data and I don't know how to solve them.
See [issue#22](https://github.com/thuiar/MMSA/issues/22) for details.

> Hi, to test the model performance of real-time video do not need to change the config file actually. You need to load the model and preprocess the video data as the same with train / test data.

Thanks!
In fact, I'm trying to do it.
But I have some problems when dealing with data and I don't know how to solve them.
See [issue#22](https://github.com/thuiar/MMSA/issues/22) for details.
