### ISSUE TITLE
about audio from dataset MOSEI

### ISSUE THREAD

**Issue by Tongyuang** [thuiar/MMSA#28]
Hi, I just want to know how the feature of audio from dataset MOSEI is calculated.

I loaded one of the datasets,
```py
filename = './aligned_50.pkl'
RawData = pickle.load(open(filename,'rb'),encoding='utf-8')
print(RawData['train']['audio'].shape)
````
the result goes:

 ```
(16326, 50, 74)
```
so it means each audio piece has a feature of shape(50,74),
but how to calculate these features from raw audio files?(like .mp3 or .wav files?)

**Comment by FlameSky-S** [comment]
The audio features are consistant with those provided by the CMU team. As mentioned in their paper: 
`We use the COVAREP software to extract acoustic features including 12 Mel-frequency cepstral coefficients, pitch, voiced/unvoiced segmenting features, glottal source parameters, peak slope parameters and maxima dispersion quotients.`

**Comment by Tongyuang** [comment]
Thank you. It helps

**Comment by xiaoxinchaoren56** [comment]
@FlameSky-S I noticed that the audio feature length of the MOSI dataset is 5. May I ask how the audio features are extracted for the MOSI dataset.
