### ISSUE TITLE
about GPU

### ISSUE THREAD

**Issue by staring-s** [thuiar/MMSA#29]
Hello, I want to know if it is possible to run this program with 4 2080Ti?

**Comment by FlameSky-S** [comment]
Not sure if I get you right, do you mean training a model with multiple gpus to accelerate the process? If that's the case, we're not planning on supporting multi-gpu training anytime soon. However, you can train multiple models with your 4 2080Tis, as long as there's enough gpu memory left.

**Comment by staring-s** [comment]
Thank you for your answer.That is, I can train the model with a 2080Ti?

**Comment by FlameSky-S** [comment]
Yes, 12GB of gpu memory is enough for most models in this framework.

**Comment by staring-s** [comment]
Thank you for your patience in answering my questions.

**Comment by FlameSky-S** [comment]
You're welcome. Let us know if you have any more questions.
