### ISSUE TITLE
请教关于准确率计算的一个问题

### ISSUE THREAD

**Issue by yxia0125** [thuiar/MMSA#3]
请问在/trains/multiTask/文件夹下的几个脚本中，第63行(以MTFN.py为例)为何使用了 y_true[m].append(labels['M'].cpu() ？

如果是计算不同modality标签预测的结果指标，是否应使用 y_true[m].append(labels[m].cpu()) ？

**Comment by iyuge2** [comment]
@yxia0125  谢谢您的建议！我们认为多模态标签反应的是人物的真实情感（通过多个模态数据综合得到的结果），而单模态标签反应了在仅有单个模态数据时，对人物情感的判断，但这种判断可能是不准确的。在这里，我们计算单模态效果时，是想测试其在预测真实人物情感时的效果。因此，我们使用了`labels['M']`。若将这个结果与多模态结果进行对比，可以体现出单模态数据的局限性。当然，如果仅仅想测试单模态情感分类的效果，是可以改成`labels[m]`的。关于这点分析，可以参考我们论文中`Table 4`的结果呈现。

**Comment by yxia0125** [comment]
明白了，谢谢
