### ISSUE TITLE
关于相关系数Corr

### ISSUE THREAD

**Issue by HEBAULC** [thuiar/MMSA#37]
作者您好，请问在SIMS数据集的回归任务中Corr值的高低代表什么？为什么EF-LSTM的Corr值和别的模型相差那么多，在多少范围是正常的呢

**Comment by Columbine21** [comment]
@HEBAULC  您好，Corr 是回归标签的皮尔逊相关系数，取值范围[-1, 1]（提供的结果都是 * 100之后保留两位小数的结果），越高表示预测值与标签值（负数表示负相关，正数表示正相关）。EF-LSTM 的数值我们再确认一下。

**Comment by HEBAULC** [comment]
> @HEBAULC 您好，Corr 是回归标签的皮尔逊相关系数，取值范围[-1, 1]（提供的结果都是 * 100之后保留两位小数的结果），越高表示预测值与标签值（负数表示负相关，正数表示正相关）。EF-LSTM 的数值我们再确认一下。

好的 谢谢您的解答

**Comment by HEBAULC** [comment]
> 

另外请问您一下，这个值小说明模型不好吗？另外取最优模型是具体用的某个指标还是多个指标呢？

**Comment by Columbine21** [comment]
嗯，这个数值应该是越大说明模型效果越好
