### ISSUE TITLE
关于pytorch版本的问题

### ISSUE THREAD

**Issue by LingFengGold** [thuiar/MMSA#39]
我看到您的默认pytorch版本至少是1.9.1，我的GPU的cuda版本不支持安装这个版本的pytorch。请问有什么好的解决方案吗？

**Comment by LingFengGold** [comment]
@Columbine21 麻烦您

**Comment by Columbine21** [comment]
请问现在按照 Readme 里面的示例代码能跑通么？还是会遇到什么 Error ，我们之前没有使用过低版本进行测试，之后可能扩展一下 @LingFengGold

**Comment by LingFengGold** [comment]
可以可以辛苦你们了，老版本1.7.1也可以运行。

**Comment by Columbine21** [comment]
嗯 好的ok
