### ISSUE TITLE
关于MMIM的复现问题

### ISSUE THREAD

**Issue by LingFengGold** [thuiar/MMSA#40]
您好！
我在使用您的代码复现MMIM时观察到main loss变nan，我并没有修改您的代码，数据也是使用您提供的/mosi/unaligned。
`MMSA - TRAIN-(mmim) [1/2/2] >> mmilb loss: 0.0042 main loss: nan  Has0_acc_2: 0.5701  Has0_F1_score: 0.4140  Non0_acc_2: 0.5971  Non0_F1_score: 0.5708  Mult_acc_5: 0.2500  Mult_acc_7: 0.2313  MAE: 1.2234  Corr: 0.3217 `
请问这是什么原因导致的呢？

**Comment by Columbine21** [comment]
@LingFengGold 同学您好，MMIM 模型是最新的多模态情感分析模型，我们正在修改，会在最新版本中同步更新（目前版本可能有些问题）。

**Comment by Columbine21** [comment]
@LingFengGold 问题已经解决了，发现是batch_size 设置的太小导致的。现在模型效果已经正常，请同学有时间测试一下
