### ISSUE TITLE
关于评价指标

### ISSUE THREAD

**Issue by zc-work** [thuiar/MMSA#45]
作者你好，关于评价指标论文中说到分类任务是acc和F1，请问主实验Table2中Acc-2、Acc-3、Acc-5和F1指标，这个F1是Acc-2还是Acc-3还是Acc-5的F1呢？

**Comment by Columbine21** [comment]
您好，MSA 领域中的 F1 通常是指 Acc-2 的 F1 Score。

**Comment by zc-work** [comment]
好的，感谢回复，最后请问Table2中的F1 Score是二分类中的Has0_F1_score还是Non0_F1_score呢？

**Comment by FlameSky-S** [comment]
您是指哪篇论文呢？一般未注明的话默认是指Non0的情况
