### ISSUE TITLE
Raw files for CMU MOSEI dataset

### ISSUE THREAD

**Issue by sumit-agrwl** [thuiar/MMSA#47]
Can the raw files for the CMU MOSEI dataset be shared? I saw that its on a Baidu server which I cannot access unfortunately.

**Comment by Columbine21** [comment]
If only the MOSEI dataset is needed, the following link may help. @sumit-agrwl  http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/

**Comment by FlameSky-S** [comment]
Hi, we've updated the Baiduyun link recently. 

Closing this issue for now.
