### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by NicholasGote** [thuiar/MMSA#5]
Dear Authors:

I was trying to repeat your results. But I found the data/Datapre.py script did not fit the raw videos in CH-SIMI.zip (downloaded from Google Drive). I tried to wrote scripts to process the raw videos, but the train/val/test split index files did not fit the raw video index. 

I am asking if it is right to use train_index.csv files to process the data.npz feature files? For example, when id '0' in the train_index.csv, if the '0'th feature in data.npz file belongs to the training set.

It would be very helpful if you can update the processed feature or the whole folder so that data/DataPre.py can process it properly.

**Comment by iyuge2** [comment]
@NicholasGote  Thanks for your attention!

- The problem of `data/Datapre.py`
We updated our `data/Datapre.py` a few days ago, which may be not compatible with the old CH-SIMS.zip.  New `data/Datapre.py` has a more convenient way to extract features from raw videos, which needs a preprocessed label file and the root dir of raw videos. Please see our codes for details. 

- The index problem
Yes. It is right for "when id '0' in the train_index.csv, if the '0'th feature in data.npz file belongs to the training set."

- The processed feature update problem
Sorry, we forgot to update our processed features in Google and Baidu Drives. Now, we have done that. You can download new features `CH_SIMS_unaligned_39.pkl` from [Baidu Yun Disk](https://pan.baidu.com/s/177hnei8ySH6IpGGeF9W8fw) [code: `g63s`] or [Google Drive](https://drive.google.com/file/d/1Zux66GJCuzsVnHgRC-DKIz4ua9YwZC3e/view?usp=sharing), which is compatible with our new code structure. The `md5 code` is `a5b2ed3844200c7fb3b8ddc750b77feb`.

**Comment by iyuge2** [comment]
It is worth noting that the `CH_SIMS_unaligned_39.pkl` is compatible with [the feature structure](https://github.com/thuiar/MMSA#dataset-feature-structure).

**Comment by NicholasGote** [comment]
Thanks a lot.
