### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by Sailormooner** [thuiar/MMSA#50]
作者您好，有一个问题想确认一下，数据集由60个视频裁剪而来，获取了2281个视频片段，每个video文件夹下的单个视频是按总视频的顺序来安放的吗？是否可以视作对话数据集呢？期待您的回复。
Hello, author, I have a question to confirm that the data set is cropped from 60 videos and 2281 video clips have been obtained. Is the single video in each video folder placed in the order of the total video? Can you think of it as a conversation data set? Thank you for your reply.

**Comment by Sailormooner** [comment]
同时还想请教您的是，在单模态的评价中，评价指标是Acc-2，Acc-2指的是二类精度，是二分类吗，二分类是仅选用消极和积极两个类别吗？那么中性被看作如何标注的呢？

**Comment by FlameSky-S** [comment]
您好，关于第一个问题，每个video下的视频（clip）是按照视频的时间顺序存放的，但是clip之间的时间间隔可能比较长，并不一定能够形成有效的对话，如果需要做对话任务的话还需要自行筛选。

评价指标ACC-2是二分类精度，细分的话有Non0_acc_2和Has0_acc_2，没有注明的话一般指Non0_acc_2，即不包含中性样本的二分类
