### ISSUE TITLE
Processed data for SIIMS dataset

### ISSUE THREAD

**Issue by sumit-agrwl** [thuiar/MMSA#51]
Can the Processed data be shared for SIIMS dataset in google drive? I can't access the baidu link here from US. Thank you in advance!

**Comment by FlameSky-S** [comment]
Hi, I've just uploaded the SIMS feature file to Google Drive. Thank you for your interest in our work!

**Comment by sumit-agrwl** [comment]
Thank you for your prompt reply. Can I know the kind of features that have been used in the SIMS dataset that has been shared?

**Comment by sumit-agrwl** [comment]
Also, can you share how did you extract 33 features from librosa, or is there any related code for that?
