### ISSUE TITLE
How to download raw data for your CH-SIMS dataset?

### ISSUE THREAD

**Issue by Fancy-Block** [thuiar/MMSA#53]
You've done a great job! But if I want to try out some other features for those three modalities, how can I download the complete dataset? The links provided on your home page only contains processed data from CH-SIMS dataset.

**Comment by FlameSky-S** [comment]
Hi, this [Baiduyun link](https://pan.baidu.com/s/1RfGj1QC7DN0PI31rQNxEqw?pwd=kevp) contains the complete CH-SIMS dataset.  Please let us know if you have trouble accessing the link

**Comment by BlackLM12138** [comment]
> Hi, this [Baiduyun link](https://pan.baidu.com/s/1RfGj1QC7DN0PI31rQNxEqw?pwd=kevp) contains the complete CH-SIMS dataset. Please let us know if you have trouble accessing the link

It seems like the link has some problems. There's only SIMS dataset in Baiduyun link. Could you check it?

**Comment by FlameSky-S** [comment]
> It seems like the link has some problems. There's only SIMS dataset in Baiduyun link. Could you check it?
This [link](https://pan.baidu.com/s/1dJ9_nR2BJrLhZD6VlgvFqw?pwd=ta0w) contains all 3 datasets. I've updated the README file.

**Comment by Fancy-Block** [comment]
Thanks! I've downloaded them successfully 👍
