### ISSUE TITLE
Where's the MOSI/label.csv ?

### ISSUE THREAD

**Issue by ShituanHu** [thuiar/MMSA#7]
I find the dataset in http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSI.zip. But can't find the label.csv，why? Or It's produced by program?  If yes, where's  the program?

**Comment by ShituanHu** [comment]
I met this problem when using https://github.com/thuiar/Self-MM

**Comment by iyuge2** [comment]
@ShituanHu 
Hi, the `label.csv` is produced by ours. We integrate that in our public features. You can download them according to [Datasets and Pre-trained Berts](https://github.com/thuiar/MMSA#datasets-and-pre-trained-berts). Best wishes!

**Comment by iyuge2** [comment]
@ShituanHu We have updated instructions in https://github.com/thuiar/Self-MM
