### ISSUE TITLE
hi,query about dataset

### ISSUE THREAD

**Issue by jun0wanan** [thuiar/MMSA#8]
你好 (●'◡'●)

      感谢你对这个代码库的不断支持，不知道能不能请教您，这个数据集合的 align 和 unalign 有 什么区别吗~~╥﹏╥...感谢！

Best，
jun0

**Comment by iyuge2** [comment]
你好，不客气～

对齐与非对齐指多模态数据中文本、音频和视频在时间维度上是否一一对应，特征文件中的align与unalign主要指音频和视频特征是否与文本中的字/单词对应。

有关这个问题，可以读一下这篇论文->[Multimodal Transformer for Unaligned Multimodal Language Sequences](https://www.aclweb.org/anthology/P19-1656.pdf)。

Best,
iyuge2

**Comment by jun0wanan** [comment]
> 你好，不客气～
> 
> 对齐与非对齐指多模态数据中文本、音频和视频在时间维度上是否一一对应，特征文件中的align与unalign主要指音频和视频特征是否与文本中的字/单词对应。
> 
> 有关这个问题，可以读一下这篇论文->[Multimodal Transformer for Unaligned Multimodal Language Sequences](https://www.aclweb.org/anthology/P19-1656.pdf)。
> 
> Best,
> iyuge2

感谢您的回复，我在跑MMSA这个code的时候 ，出现了

`ImportError: cannot import name 'MultimodalBertForSequenceClassification' from` 在BERT_MAG.py 这个文件中 即，pytorch_transformers 无法引入 MultimodalBertForSequenceClassification 。通过谷歌也搜不到相关问题的解决办法，不知道您知道这个问题的解决方法吗~

**Comment by iyuge2** [comment]
不客气～
我们在整合代码时，发现MAG的作者重新更新了自己的代码[BERT_multimodal_transformer](https://github.com/WasifurRahman/BERT_multimodal_transformer)，由于时间关系我们还没有将其整合到这个仓库中。因此我们的代码暂不支持BERT_MAG方法。如果你不需要用到这个方法可以直接删除相应的模块即可，或者你也可以参照原作者代码进行修改。谢谢！
