### ISSUE TITLE
Regarding the Results in result-stat.md

### ISSUE THREAD

**Issue by Haoyu-ha** [thuiar/MMSA#81]
Are these results using a single random seed or an average of the results corresponding to five random seeds? Are the results from all models with the same random seed?

**Comment by Columbine21** [comment]
Yes, we report the average model performance with five random seeds (for fair comparison we use the same for different model.)

**Comment by Haoyu-ha** [comment]
Thanks for your reply. Could you tell me what these five seeds are? Is it from 1111 to 1115 or some other value?

**Comment by Columbine21** [comment]
[1111, 1112, 1113, 1114, 1115] are used here. But in fact, deviations may still exist due to different version python labs or different types of gpus.

**Comment by Haoyu-ha** [comment]
OK. Thank you for your help!
