### ISSUE TITLE
我该如何使用MMSA来训练我的模型？要怎么修改源代码呢？

### ISSUE THREAD

**Issue by HEU2021201622** [thuiar/MMSA#82]
Code structure里是空的，没办法参考，而且看起来训练过程和模型耦合在一块了，不太方便使用。还有一点，似乎要用3.10以上的版本才能支持dict | str运算符，所以这个repo只能支持3.10以上版本。

**Comment by HEU2021201622** [comment]
已经跑通了，主要修改的是ATIO.py和AMIO.py里的两个文件以及向train和model文件下里添加model.py的文件，最后向configregression.json或者另一个json文件里加配置参数。

**Comment by cyang810** [comment]
您好，请问dict |str运算符怎么解决呢

**Comment by Columbine21** [comment]
@cyang810 这个是 Python 3.10 环境的特性，现在如果直接想使用 MMSA 的话需要配一个 python 3.10+ 的环境

**Comment by cyang810** [comment]
好的，感谢你的回复
