### ISSUE TITLE
Reporting problems with TFR-Net on the SIMS dataset

### ISSUE THREAD

**Issue by Haoyu-ha** [thuiar/MMSA#90]
TFR-Net does not work with default parameters on SIMS dataset, it reports an error.

`   
 assert self.head_dim * num_heads == self.embed_dim, "embed_dim must be divisible by num_heads"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: embed_dim must be divisible by num_heads
`

**Comment by Columbine21** [comment]
TFR-Net 在 SIMS 运行时需要把num_heads 设置成1。

**Comment by Haoyu-ha** [comment]
> TFR-Net 在 SIMS 运行时需要把num_heads 设置成1。

好的好的，非常感谢回复~    之前是这样跑的，但是担心是不是有问题 就还是问了一下。
